//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaPulse.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invitado
    {
        public System.Guid Id { get; set; }
        public string Correo { get; set; }
        public Nullable<System.Guid> EventoId { get; set; }
        public Nullable<int> EstadoId { get; set; }
    
        public virtual Estado_Invitado Estado_Invitado { get; set; }
        public virtual Evento Evento { get; set; }
    }
}
